name: "Publish Docker Image"

on:
  workflow_call:
    # No inputs needed at this time

jobs:
  docker_publish:
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write

    env:
      DOCKER_IO_REGISTRY: docker.io
      DOCKER_IO_IMAGE_NAME_ALL: helmuthva/aignostics-python-sdk
      DOCKER_IO_IMAGE_NAME_SLIM: helmuthva/aignostics-python-sdk-slim

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install dev tools
        shell: bash
        run: .github/workflows/_install_dev_tools.bash

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1


      - name: Log in to Docker Hub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:

          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}



      - name: Log in to GitHub container registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io

          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: "(all target): Extract metadata (tags, labels) for Docker"
        id: meta-all
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:


          images: |
            ${{ env.DOCKER_IO_IMAGE_NAME_ALL }}
            ghcr.io/${{ github.repository }}



          tags: |
            # set latest tag for releases
            type=raw,value=latest
            # set semver tags from git tags (v1.2.3 -> 1.2.3, 1.2, 1)
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}


      - name: "(slim target): Extract metadata (tags, labels) for Docker"
        id: meta-slim
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:


          images: |
            ${{ env.DOCKER_IO_IMAGE_NAME_SLIM }}
            ghcr.io/${{ github.repository }}-slim



          tags: |
            # set latest tag for releases
            type=raw,value=latest
            # set semver tags from git tags (v1.2.3 -> 1.2.3, 1.2, 1)
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}



      - name: "(all target): Build and push Docker image"
        id: build-and-push-all
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          file: ./Dockerfile
          target: all
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-all.outputs.tags }}
          labels: ${{ steps.meta-all.outputs.labels }}



      - name: "(slim target): Build and push Docker image"
        id: build-and-push-slim
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          file: ./Dockerfile
          target: slim
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-slim.outputs.tags }}
          labels: ${{ steps.meta-slim.outputs.labels }}
